# <center><span style="color:red;font-style:normal;font-family:Georgia">RANDOM FOREST</span></center>

## <span style="color:blue;font-style:normal;font-family:Georgia">Algoritmo random forest.</span>

In [17]:
# 1. Importar las librerias.
# 2. Importar data.
# 3. Separar variables dependientes de variables independientes.
# 4. Normalizar los valores de las variables independientes.
# 5. Dividir en data de entrenamiento y testeo.
# 6. Entrenar el algoritmo con la data de entrenamiento.
# 7. Ver su eficiencia usando la data de testeo.
# 8. Aplicar el modelo para predecir.
# 9. Importancia de las variables.


## <span style="color:red;font-style:normal;font-family:Georgia">1. Importar las librerias.</span>

In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

## <span style="color:red;font-style:normal;font-family:Georgia">2. Importar la data.</span>

In [3]:
data=pd.read_csv("heart.csv")
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

## <span style="color:red;font-style:normal;font-family:Georgia">3. Separamos variables dependientes de independientes.</span>

### <span style="color:red;font-style:normal;font-family:Georgia">3.1. Variables dependientes.</span>

In [5]:
var_dep=data["target"] # filtro o cojo la variable dependiente
var_dep.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

### <span style="color:red;font-style:normal;font-family:Georgia">3.2. Variables independientes.</span>

In [7]:
var_ind=data.drop("target",axis=1) # eliminio la variable dependiente para quedarme solo con las independientes (que son las que se normalizan)
var_ind.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

### <span style="color:red;font-style:normal;font-family:Georgia">4. Normalizar los valores de las variables independientes.</span>

In [8]:
var_ind_norm=StandardScaler().fit_transform(var_ind) # normalizacion (dato -media)/(desviacion standar)
var_ind_norm

array([[ 0.9521966 ,  0.68100522,  1.97312292, ..., -2.27457861,
        -0.71442887, -2.14887271],
       [-1.91531289,  0.68100522,  1.00257707, ..., -2.27457861,
        -0.71442887, -0.51292188],
       [-1.47415758, -1.46841752,  0.03203122, ...,  0.97635214,
        -0.71442887, -0.51292188],
       ...,
       [ 1.50364073,  0.68100522, -0.93851463, ..., -0.64911323,
         1.24459328,  1.12302895],
       [ 0.29046364,  0.68100522, -0.93851463, ..., -0.64911323,
         0.26508221,  1.12302895],
       [ 0.29046364, -1.46841752,  0.03203122, ..., -0.64911323,
         0.26508221, -0.51292188]])

## <span style="color:red;font-style:normal;font-family:Georgia">5. Dividir en data de entrenamiento y testeo.</span>

In [9]:
x_train,x_test,y_train,y_test=train_test_split(var_ind_norm,var_dep,test_size=0.25,shuffle=True,random_state=125)
#shuffle=True -> separa aletoriamente
#test_size = 0.25 -> 25% de toda la data, sera de testeo
#random_state=125 -> que sea reproducible -> ledas cualquier numero entero

## <span style="color:red;font-style:normal;font-family:Georgia">6. Entrenar el algoritmo con la data de entrenamiento.</span>

In [10]:
rf=RandomForestClassifier(max_depth=4,n_estimators=100) # esto solo construye el modelo
# max_depth -> numero de ramas
# n_estimators -> numero de arboles

In [11]:
rf.fit(x_train,y_train) # fit -> optimizar -> entrenar
print('ready')

ready


## <span style="color:red;font-style:normal;font-family:Georgia">7. Ver su eficiencia usando la data de testeo.</span>

In [12]:
rf.score(x_test,y_test) # score -> puntaje -> que tan bien hace su trabajo

0.8157894736842105

## <span style="color:red;font-style:normal;font-family:Georgia">8. Aplicar el modelo para predecir.</span>

In [13]:
x_test.shape # veo dimension

(76, 13)

In [14]:
x_test[0] # este es un ejemplo de una nueva persona que viene

array([-1.69473524,  0.68100522, -0.93851463, -0.77809263, -0.52689046,
       -0.41763453,  0.89896224, -0.42186226, -0.69663055,  0.13837295,
       -0.64911323, -0.71442887,  1.12302895])

In [15]:
x_test[0].shape # la dimensino no es correcta (13,1), yo necesito una dimsion que sea 1,13

(13,)

In [16]:
x_test[0].reshape(1,13) # cambia la dimension de 13,1 a 1,13

array([[-1.69473524,  0.68100522, -0.93851463, -0.77809263, -0.52689046,
        -0.41763453,  0.89896224, -0.42186226, -0.69663055,  0.13837295,
        -0.64911323, -0.71442887,  1.12302895]])

In [17]:
rf.predict(x_test[0].reshape(1,13))
# basado en mi modelo, esta persona usara el seguro con una probabilidad de .84
# para predecir solo uno

array([0], dtype=int64)

In [18]:
rf.predict(x_test) # para predecir de un grupo

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0], dtype=int64)

## <span style="color:red;font-style:normal;font-family:Georgia">9. Importancia de las variables.</span>

In [19]:
rf.feature_importances_ # importancia esta basada en la data de ENTRENAMIENTO

array([0.04586848, 0.03659757, 0.17277975, 0.03749129, 0.03426616,
       0.00225552, 0.00870763, 0.1206624 , 0.09984711, 0.10854302,
       0.0548148 , 0.14586547, 0.1323008 ])

## <span style="color:red;font-style:normal;font-family:Georgia">6. Como escojo un buen modelo.</span>

In [20]:
#numero_de_repeticiones = [1,2,3,..,30]
numero_de_arboles = [5,50,100,200,500,1000,5000]

In [21]:
for num in numero_de_arboles:
    for rep in numero_de_repeticiones:
        rf = RandomForestClassifier(max_depth=5,n_estimators=num)
        rf.fit(x_train,y_train)
        print('numero de arboles ',num,'precision: ',rf.score(x_test,y_test))

NameError: name 'numero_de_repeticiones' is not defined